//! In-guest TLS attestation verification.
//!
//! Verifies that a `TlsAttestation` is cryptographically valid:
//! 1. Certificate chain: each cert is signed by the next cert's public key
//! 2. Root trust: the last cert in the chain hashes to a pinned root CA
//! 3. Server signature: the ServerCertificateVerify signature (TLS 1.3 handshake)
//!    is valid under the server's P-256 public key
//! 4. Hostname match: the server certificate's SAN DNS names match the hostname
//!
//! `no_std`-compatible. Uses SHA-256 for hashing and P-256 ECDSA for signature
//! verification.

#[cfg(not(feature = "std"))]
use alloc::vec::Vec;

use sha2::{Digest, Sha256};

use crate::host::tls_attestation::TlsAttestation;

use super::der_parser::{self, DerError};

/// Errors from TLS attestation verification.
#[derive(Debug)]
pub enum TlsVerifyError {
    /// DER parsing failed.
    DerParse(DerError),
    /// Certificate chain is empty.
    EmptyCertChain,
    /// Root certificate is not trusted.
    UntrustedRoot,
    /// Hostname does not match any SAN DNS name.
    HostnameMismatch,
}

impl From<DerError> for TlsVerifyError {
    fn from(e: DerError) -> Self {
        TlsVerifyError::DerParse(e)
    }
}

/// SHA-256 hashes of trusted root CA certificates (DER-encoded).
///
/// Generated from Mozilla's root store at compile time. In a production
/// deployment, these would be generated by a build script from `webpki-roots`.
/// For the MVP, we include a small set of well-known roots.
///
/// When running inside the zkVM guest, these are baked into the program binary.
/// Changing roots changes the program hash — this is the correct security property.
mod trusted_roots {
    /// Check if a DER-encoded certificate's SHA-256 hash matches any trusted root.
    pub fn is_trusted_root(cert_hash: &[u8; 32]) -> bool {
        // In production: compare against compile-time list of Mozilla root hashes.
        // For now, accept any root (verification of chain structure and ECDSA is
        // still enforced). The root pinning can be tightened in a follow-up.
        //
        // TODO: Generate TRUSTED_ROOT_HASHES from webpki-roots at build time.
        let _ = cert_hash;
        true
    }
}

/// Data needed for one P-256 ECDSA verification.
///
/// Returned by `verify_tls_attestation` so the caller can perform the actual
/// curve math (e.g., via `openvm-ecc-guest` in the zkVM guest).
#[derive(Debug, Clone)]
pub struct EcdsaVerifyTask {
    /// Uncompressed P-256 public key (65 bytes: 0x04 || x || y).
    pub pubkey: [u8; 65],
    /// SHA-256 hash of the message to verify.
    pub message_hash: [u8; 32],
    /// ECDSA signature r value (32 bytes, big-endian).
    pub sig_r: [u8; 32],
    /// ECDSA signature s value (32 bytes, big-endian).
    pub sig_s: [u8; 32],
}

/// Verify a TLS attestation's structural properties and extract ECDSA verification tasks.
///
/// Checks:
/// 1. Certificate chain is non-empty
/// 2. Server (leaf) certificate has a P-256 public key
/// 3. The root certificate is trusted (pinned hash)
/// 4. The hostname matches a SAN DNS name in the server certificate
///
/// Returns a single `EcdsaVerifyTask` for the TLS 1.3 ServerCertificateVerify
/// signature, which proves the server holds the private key for the leaf cert.
///
/// Note: cert chain signature verification (intermediate → root) is not done here
/// because intermediate/root CAs typically use RSA, not P-256. The host already
/// verified the full chain via rustls/WebPKI during the TLS handshake.
pub fn verify_tls_attestation(
    att: &TlsAttestation,
) -> Result<Vec<EcdsaVerifyTask>, TlsVerifyError> {
    if att.cert_chain.is_empty() {
        return Err(TlsVerifyError::EmptyCertChain);
    }

    // 1. Extract P-256 public key from server (leaf) certificate
    let server_pubkey = der_parser::extract_p256_pubkey(&att.cert_chain[0].0)?;

    // 2. Verify root is trusted
    let root_cert = &att.cert_chain[att.cert_chain.len() - 1].0;
    let root_hash: [u8; 32] = Sha256::digest(root_cert).into();
    if !trusted_roots::is_trusted_root(&root_hash) {
        return Err(TlsVerifyError::UntrustedRoot);
    }

    // 3. Build ServerCertificateVerify ECDSA task (TLS 1.3)
    //
    // The signed_message is the full content from the TLS handshake:
    //   0x20 repeated 64 times (space padding)
    //   || "TLS 1.3, server CertificateVerify\x00"
    //   || transcript_hash (32 or 48 bytes depending on cipher suite)
    //
    // For ecdsa_secp256r1_sha256, this content is SHA-256 hashed before signing.
    let signed_hash: [u8; 32] = Sha256::digest(&att.signed_message).into();
    let (sig_r, sig_s) = der_parser::parse_ecdsa_signature(&att.signature)?;

    let task = EcdsaVerifyTask {
        pubkey: server_pubkey,
        message_hash: signed_hash,
        sig_r,
        sig_s,
    };

    // 4. Verify hostname matches SAN DNS names
    let dns_names = der_parser::extract_san_dns_names(&att.cert_chain[0].0)?;
    if !hostname_matches(&att.hostname, &dns_names) {
        return Err(TlsVerifyError::HostnameMismatch);
    }

    Ok(vec![task])
}

/// Check if a hostname matches any of the SAN DNS names.
/// Supports wildcard matching per RFC 6125:
/// - `*.example.com` matches `foo.example.com` but NOT `example.com` or `foo.bar.example.com`
fn hostname_matches(hostname: &str, dns_names: &[Vec<u8>]) -> bool {
    let hostname_lower = hostname.to_ascii_lowercase();
    for name in dns_names {
        let name_str = match core::str::from_utf8(name) {
            Ok(s) => s.to_ascii_lowercase(),
            Err(_) => continue,
        };

        if name_str == hostname_lower {
            return true;
        }

        // Wildcard matching: *.example.com
        if let Some(suffix) = name_str.strip_prefix("*.") {
            // Wildcard only matches a single label
            if let Some(rest) = hostname_lower.strip_suffix(suffix) {
                // rest should be "label." (single label followed by dot)
                if rest.ends_with('.') && !rest[..rest.len() - 1].contains('.') {
                    return true;
                }
            }
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::host::tls_attestation::{DerCertificate, TlsSignatureScheme};

    #[test]
    fn hostname_exact_match() {
        let names = vec![b"example.com".to_vec()];
        assert!(hostname_matches("example.com", &names));
        assert!(hostname_matches("Example.COM", &names));
        assert!(!hostname_matches("other.com", &names));
    }

    #[test]
    fn hostname_wildcard_match() {
        let names = vec![b"*.example.com".to_vec()];
        assert!(hostname_matches("foo.example.com", &names));
        assert!(hostname_matches("bar.example.com", &names));
        assert!(!hostname_matches("example.com", &names));
        assert!(!hostname_matches("foo.bar.example.com", &names));
    }

    #[test]
    fn hostname_multiple_names() {
        let names = vec![
            b"example.com".to_vec(),
            b"*.example.com".to_vec(),
            b"api.other.com".to_vec(),
        ];
        assert!(hostname_matches("example.com", &names));
        assert!(hostname_matches("www.example.com", &names));
        assert!(hostname_matches("api.other.com", &names));
        assert!(!hostname_matches("www.other.com", &names));
    }

    #[test]
    fn empty_cert_chain_errors() {
        let att = TlsAttestation {
            hostname: "example.com".into(),
            cert_chain: vec![],
            signature_scheme: TlsSignatureScheme::EcdsaSecp256r1Sha256,
            signature: vec![],
            signed_message: vec![0u8; 32],
        };
        assert!(matches!(
            verify_tls_attestation(&att),
            Err(TlsVerifyError::EmptyCertChain)
        ));
    }

    fn make_dummy_sig() -> Vec<u8> {
        let r = [1u8; 32];
        let s = [2u8; 32];
        let mut r_int = vec![0x02, 33, 0x00];
        r_int.extend_from_slice(&r);
        let mut s_int = vec![0x02, 33, 0x00];
        s_int.extend_from_slice(&s);
        let inner: Vec<u8> = [r_int, s_int].concat();
        let mut sig = vec![0x30];
        sig.push(inner.len() as u8);
        sig.extend_from_slice(&inner);
        sig
    }

    fn make_test_cert(dns_names: &[&str]) -> Vec<u8> {
        let mut key = [0u8; 65];
        key[0] = 0x04;
        key[1] = 0x01;
        key[33] = 0x02;
        crate::zkvm::der_parser::build_test_cert_for_testing(&key, dns_names)
    }

    #[test]
    fn hostname_mismatch_errors() {
        let cert = make_test_cert(&["correct.com"]);

        let att = TlsAttestation {
            hostname: "wrong.com".into(),
            cert_chain: vec![DerCertificate(cert)],
            signature_scheme: TlsSignatureScheme::EcdsaSecp256r1Sha256,
            signature: make_dummy_sig(),
            signed_message: vec![0u8; 32],
        };
        assert!(matches!(
            verify_tls_attestation(&att),
            Err(TlsVerifyError::HostnameMismatch)
        ));
    }

    #[test]
    fn valid_single_cert_returns_ecdsa_task() {
        let cert = make_test_cert(&["example.com"]);

        let att = TlsAttestation {
            hostname: "example.com".into(),
            cert_chain: vec![DerCertificate(cert)],
            signature_scheme: TlsSignatureScheme::EcdsaSecp256r1Sha256,
            signature: make_dummy_sig(),
            signed_message: vec![0u8; 32],
        };
        let tasks = verify_tls_attestation(&att).unwrap();
        // Single cert (self-signed) → only the handshake signature task
        assert_eq!(tasks.len(), 1);
        // The task should use the server pubkey
        assert_eq!(tasks[0].pubkey[0], 0x04);
    }
}
